language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0

services:
  - apc
  - memcache
  - memcached

before_script:
  - composer update
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != '7.0' || '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then phpenv config-add .travis/phpenv/apc-$TRAVIS_PHP_VERSION.ini; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != '7.0' || '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then phpenv config-add .travis/phpenv/memcache.ini; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != '7.0' || '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then phpenv config-add .travis/phpenv/memcached.ini; fi"

script:
  - ./vendor/bin/phpunit
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != '7.0' || '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then ./vendor/bin/phpcs -p --report=full --extensions=php --standard=.travis/phpcs/Joomla/ruleset.xml src/; fi"
