language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0

services:
  - memcache
  - memcached

before_script:
  - composer update
  - if [ '$TRAVIS_PHP_VERSION' != '7.0' || "$TRAVIS_PHP_VERSION" != 'hhvm' ]; then phpenv config-add .travis/phpenv/memcache.ini; fi
  - if [ '$TRAVIS_PHP_VERSION' != '7.0' || "$TRAVIS_PHP_VERSION" != 'hhvm' ]; then phpenv config-add .travis/phpenv/memcached.ini; fi

script:
  - ./vendor/bin/phpunit
  - if [[ "$TRAVIS_PHP_VERSION" != '7.0' || "$TRAVIS_PHP_VERSION" != 'hhvm' ]]; then ./vendor/bin/phpcs -p --report=full --extensions=php --standard=.travis/phpcs/Joomla/ruleset.xml src/; fi
